# Generated by Django 5.2.1 on 2025-05-30 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimeapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='state',
            new_name='address',
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(max_length=10),
        ),
    ]
